### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by HenDog273** [apexskier/homebridge-eero-presence#3]
Hi, sorry if this is a stupid question. I'm trying to set this plugin up on homebridge using pi terminal. Each time I run 'npm run auth' it returns missing script. Any ideas?

**Comment by apexskier** [comment]
Where are you running the script from?

**Comment by apexskier** [comment]
You'll need to run it from plugin's directory.

e.g.

```sh
HOMEBRIDGE_PLUGIN_PATH=/var/lib/homebridge/node_modules
HOMEBRIDGE_NODEJS_PATH=/opt/homebridge/bin
cd "$HOMEBRIDGE_PLUGIN_PATH/@apexskier/homebridge-eero-presence"
PATH="$PATH:$HOMEBRIDGE_NODEJS_PATH" npm run auth
```

The values for the paths might be different, you can get them from the homebridge UI's system information panel.

![Homebridge AEA5 - Safari - 2024-03-13 at 17 28 29@2x](https://github.com/apexskier/homebridge-eero-presence/assets/329222/4da2c0f3-33a3-4fbf-be13-59fbc72b73af)

**Comment by apexskier** [comment]
If that doesn't help, can you copy (ideally, or screenshot if you can't copy) the terminal output of what you're running and what the output is?

**Comment by HenDog273** [comment]
That worked, thank you very much. You're right I didn't run it from the correct directory.

Is there a way to look for a specific device name/IP address rather than a device type?

For example if there's multiple computers connected. Is it possible to trigger occupancy from a specific device?

**Comment by apexskier** [comment]
> Is there a way to look for a specific device name/IP address rather than a device type?

Not at the moment, but that'd be possible to add. The logic for determining if a connected device counts towards occupancy is:

https://github.com/apexskier/homebridge-eero-presence/blob/71ae0d61e595e1e410e97b3746ba8aa8ac98baf0/src/platform.ts#L174-L185

The `device` object there has a bunch of stuff, including MAC address, hostname, display name, nickname, and IP (v4 and v6).

I'm not a fan of doing this by IP/MAC since it's harder to maintain (I don't statically allocate IP for personal devices in my home and iOS defaults to "private devices" - so IP/MAC will rotate over time). I also wanted to support guests as much as possible, and I don't know what their device's are named.
